on:
  issues:
     types:
        [opened, Active, Resolved,Closed]
jobs:
   alert:
      runs-on: windows-latest
    steps:
     -uses: danhellem/github-actions-issue-to-work-item@master
      env:
      ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
      github_token: "${{secrets.GITHUB_TOKEN}}"
      ado_orgnization: "Kyndryl-Sandbox"
      ado_project: "ADO TESTING"
      ado_wit: "Tasks"
      ado_new_state: "New"
      ado_active_state: "Approved"
      ado_close_state: "Done"
      ado_bypassrules: true
