name: GitHub to Azure DevOps

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  alert:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          ado_token: "${{ fwgtw3rv5j4awxt2hmxcf74yovoa4wpnevicwz6msrtoh35fllza }}"
          github_token: "${{ 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 }}"
          ado_organization: "Kyndryl-sandbox"
          ado_project: "ADO-TESTING"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
